/**
 * Store constants.
 *
 * @package
 * @since 1.0.0
 */

export const STORE_NAME = 'wp-agent/chat';

export const ACTION_TYPES = {
	SET_CONVERSATION_ID: 'SET_CONVERSATION_ID',
	SET_POST_ID: 'SET_POST_ID',
	ADD_MESSAGE: 'ADD_MESSAGE',
	SET_MESSAGES: 'SET_MESSAGES',
	SET_IS_STREAMING: 'SET_IS_STREAMING',
	APPEND_STREAMING_CONTENT: 'APPEND_STREAMING_CONTENT',
	SET_STREAMING_CONTENT: 'SET_STREAMING_CONTENT',
	FINALIZE_STREAMING: 'FINALIZE_STREAMING',
	SET_ERROR: 'SET_ERROR',
	SET_IS_LOADING: 'SET_IS_LOADING',
	SET_HAS_API_KEY: 'SET_HAS_API_KEY',
	RESET_CONVERSATION: 'RESET_CONVERSATION',
	ADD_PENDING_ACTION: 'ADD_PENDING_ACTION',
	CLEAR_PENDING_ACTIONS: 'CLEAR_PENDING_ACTIONS',
};
